openapi: 3.0.0
info:
  title: Delete Profile API
  version: 1.0.0
paths:
  /users/profiles/{userId}:
    delete:
      summary: Eliminar un perfil de usuario por ID
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Perfil eliminado correctamente
        '404':
          description: Perfil no encontrado
