version: '3.9'
services:
  db:
    image: mysql:8
    container_name: category-db-list
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: catalog
    ports:
      - "3316:3306"
  app:
    build: .
    container_name: list-categories-service
    ports:
      - "3019:3019"
    depends_on:
      - db
    env_file:
      - .env
