version: '3.9'
services:
  db:
    image: mysql:8
    container_name: product-db-read
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: catalog
    ports:
      - "3310:3306"
  app:
    build: .
    container_name: read-product-service
    ports:
      - "3013:3013"
    depends_on:
      - db
    env_file:
      - .env