version: '3.9'
services:
  db:
    image: mysql:8
    container_name: product-db-list
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: catalog
    ports:
      - "3313:3306"
  app:
    build: .
    container_name: list-products-service
    ports:
      - "3016:3016"
    depends_on:
      - db
    env_file:
      - .env