openapi: 3.0.0
info:
  title: List Addresses API
  version: 1.0.0
paths:
  /users/addresses:
    get:
      summary: Listar direcciones de un usuario
      parameters:
        - in: query
          name: user_id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Lista de direcciones
        '400':
          description: Falta user_id
        '500':
          description: Error interno