openapi: 3.0.0
info:
  title: Update Address API
  version: 1.0.0
paths:
  /users/addresses:
    put:
      summary: Actualiza una dirección existente
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                _id:
                  type: string
                street:
                  type: string
                city:
                  type: string
                state:
                  type: string
                postal_code:
                  type: string
                country:
                  type: string
                is_primary:
                  type: boolean
      responses:
        '200':
          description: Dirección actualizada
        '400':
          description: Falta el ID
        '404':
          description: Dirección no encontrada
        '500':
          description: Error interno